const roles = {
    staff: 'staff',
    client: 'client',
    admin: 'admin',
    guest: 'guest'
}

module.exports.dispatchTable = {
    '/' : [roles.guest, roles.staff, roles.admin, roles.client],
    '/login' : [roles.guest, roles.staff],
    '/back-office' : [roles.admin, roles.guest, roles.staff, roles.client],
    '/logout' : [roles.client, roles.staff],
    '/staff-logout' : [roles.staff, roles.admin],
    '/register': [roles.guest, roles.staff],
    '/myAccount': [roles.client, roles.staff],
    '/shopcart': [roles.client, roles.guest, roles.staff],
    '/shopcart/product-quantity-update': [roles.client, roles.staff],
    '/shopcart/product-quantity-get' : [roles.client, roles.staff],
    '/product-management/renderPage': [roles.staff, roles.admin],
    '/product-management/add-product': [roles.staff, roles.admin],
    '/product-management/update-product': [roles.staff, roles.admin],
    '/product-management/edit-product/:id' : [roles.staff, roles.admin],
    '/product-management/change-product-active' : [roles.staff, roles.admin],
    '/product-management/add-product-page': [roles.staff, roles.admin],
    '/product-management/upload-image-page/:id': [roles.staff, roles.admin],
    '/order-management/renderPage' : [roles.staff, roles.admin],
    '/order-management/update-order-status' : [roles.staff, roles.admin],
    '/users-management/renderPage' : [roles.staff, roles.admin],
    '/users-management/update-user-status' : [roles.staff, roles.admin],
    '/staff-management' : [roles.admin, roles.staff],
    '/staff-management/get-all' : [roles.staff, roles.admin],
    '/staff-management/create-staff-user' : [roles.staff, roles.admin],
    '/products' : [roles.guest, roles.client, roles.admin, roles.staff],
    '/products/getByCategory' : [roles.guest, roles.client, roles.admin, roles.staff],
    '/products/add-to-cart' : [roles.guest, roles.client, roles.admin, roles.staff],
    '/products/remove-from-cart' : [roles.guest, roles.client, roles.admin, roles.staff],
    '/checkout' : [roles.guest, roles.client, roles.staff],
    '/checkout/paypal' : [roles.client, roles.staff],
    '/checkout/paypal/create-order/:id' : [roles.client, roles.staff],
    '/checkout/paypal/continue-order' : [roles.client, roles.staff],
    '/checkout/paypal/orderid' : [roles.client, roles.staff],
    '/checkout/capture-transaction' : [roles.client, roles.staff],
    '/myOrders/renderPage' : [roles.client, roles.staff],
    '/myOrders/get-orders/:id' : [roles.client, roles.staff],
    '/myOrders/order-details/:id' : [roles.client, roles.staff],
    '/myOrders/cancel-order' : [roles.client, roles.staff],
    '/reports-orders' : [roles.staff, roles.admin],
    '/reports-orders/get-orders' : [roles.staff, roles.admin],
    '/create-roles' : [roles.staff, roles.admin],
    '/create-roles/create-permission' : [roles.staff, roles.admin],
    '/create-roles/create-role' : [roles.staff, roles.admin],
    '/create-roles/update-role' : [roles.staff, roles.admin],
    '/roles/delete-role' : [roles.staff, roles.admin],
    '/users-roles/get-users-roles' : [roles.staff, roles.admin],
    '/users-roles/assignnew-role' : [roles.staff, roles.admin],
    '/users-roles/delete-relation' : [roles.staff, roles.admin],
    '/users-permissions' : [roles.staff, roles.admin],
    '/audit-log' : [roles.staff, roles.admin],
    '/error-log-file' : [roles.staff, roles.admin],
    '/config-email/create-order' : [roles.staff, roles.admin],
    '/config-email/create-order/save-global-configurations' : [roles.staff, roles.admin],
    '/config-email/create-order/save-extra-configurations': [roles.staff, roles.admin],
    '/config-email/paid-order' : [roles.staff, roles.admin],
    '/config-email/paid-order/save-global-configurations' : [roles.staff, roles.admin],
    '/config-email/paid-order/save-extra-configurations' : [roles.staff, roles.admin],
    '/import-products' : [roles.staff, roles.admin],
    '/target-groups' : [roles.staff, roles.admin],
    '/target-groups/create-target-group' : [roles.staff, roles.admin],
    '/new-target-group' : [roles.staff, roles.admin],
    '/new-target-group/add-to-target-group' : [roles.staff, roles.admin],
    '/promotions' : [roles.staff, roles.admin],
    '/new-promotion' : [roles.staff, roles.admin],
    '/promotions/create-promotion' : [roles.staff, roles.admin],
    '/promotions/create-promotion/check-name' : [roles.staff, roles.admin]
}

module.exports.whitelistURLs = [
    '/css/bootstrap.min.css.map',
    '/js/bootstrap.bundle.min.js.map'
]